<option value="Afghanistan" <?php selected( $value,'Afghanistan');?> ><?php _e('Afghanistan','profile-grid');?></option>
<option value="Åland Islands" <?php selected( $value,'Åland Islands');?> ><?php _e('Åland Islands','profile-grid');?></option>
<option value="Albania" <?php selected( $value,'Albania');?> ><?php _e('Albania','profile-grid');?></option>
<option value="Algeria" <?php selected( $value,'Algeria');?> ><?php _e('Algeria','profile-grid');?></option>
<option value="American Samoa" <?php selected( $value,'American Samoa');?> ><?php _e('American Samoa','profile-grid');?></option>
<option value="Andorra" <?php selected( $value,'Andorra');?> ><?php _e('Andorra','profile-grid');?></option>
<option value="Angola" <?php selected( $value,'Angola');?> ><?php _e('Angola','profile-grid');?></option>
<option value="Anguilla" <?php selected( $value,'Anguilla');?> ><?php _e('Anguilla','profile-grid');?></option>
<option value="Antarctica" <?php selected( $value,'Antarctica');?> ><?php _e('Antarctica','profile-grid');?></option>
<option value="Antigua and Barbuda" <?php selected( $value,'Antigua and Barbuda');?> ><?php _e('Antigua and Barbuda','profile-grid');?></option>
<option value="Argentina" <?php selected( $value,'Argentina');?> ><?php _e('Argentina','profile-grid');?></option>
<option value="Armenia" <?php selected( $value,'Armenia');?> ><?php _e('Armenia','profile-grid');?></option>
<option value="Aruba" <?php selected( $value,'Aruba');?> ><?php _e('Aruba','profile-grid');?></option>
<option value="Australia" <?php selected( $value,'Australia');?> ><?php _e('Australia','profile-grid');?></option>
<option value="Austria" <?php selected( $value,'Austria');?> ><?php _e('Austria','profile-grid');?></option>
<option value="Azerbaijan" <?php selected( $value,'Azerbaijan');?> ><?php _e('Azerbaijan','profile-grid');?></option>
<option value="Bahamas" <?php selected( $value,'Bahamas');?> ><?php _e('Bahamas','profile-grid');?></option>
<option value="Bahrain" <?php selected( $value,'Bahrain');?> ><?php _e('Bahrain','profile-grid');?></option>
<option value="Bangladesh" <?php selected( $value,'Bangladesh');?> ><?php _e('Bangladesh','profile-grid');?></option>
<option value="Barbados" <?php selected( $value,'Barbados');?> ><?php _e('Barbados','profile-grid');?></option>
<option value="Belarus" <?php selected( $value,'Belarus');?> ><?php _e('Belarus','profile-grid');?></option>
<option value="Belgium" <?php selected( $value,'Belgium');?> ><?php _e('Belgium','profile-grid');?></option>
<option value="Belize" <?php selected( $value,'Belize');?> ><?php _e('Belize','profile-grid');?></option>
<option value="Benin" <?php selected( $value,'Benin');?> ><?php _e('Benin','profile-grid');?></option>
<option value="Bermuda" <?php selected( $value,'Bermuda');?> ><?php _e('Bermuda','profile-grid');?></option>
<option value="Bhutan" <?php selected( $value,'Bhutan');?> ><?php _e('Bhutan','profile-grid');?></option>
<option value="Bolivia" <?php selected( $value,'Bolivia');?> ><?php _e('Bolivia','profile-grid');?></option>
<option value="Bosnia and Herzegovina" <?php selected( $value,'Bosnia and Herzegovina');?> ><?php _e('Bosnia and Herzegovina','profile-grid');?></option>
<option value="Botswana" <?php selected( $value,'Botswana');?> ><?php _e('Botswana','profile-grid');?></option>
<option value="Bouvet Island" <?php selected( $value,'Bouvet Island');?> ><?php _e('Bouvet Island','profile-grid');?></option>
<option value="Brazil" <?php selected( $value,'Brazil');?> ><?php _e('Brazil','profile-grid');?></option>
<option value="British Indian Ocean Territory" <?php selected( $value,'British Indian Ocean Territory');?> ><?php _e('British Indian Ocean Territory','profile-grid');?></option>
<option value="Brunei Darussalam" <?php selected( $value,'Brunei Darussalam');?> ><?php _e('Brunei Darussalam','profile-grid');?></option>
<option value="Bulgaria" <?php selected( $value,'Bulgaria');?> ><?php _e('Bulgaria','profile-grid');?></option>
<option value="Burkina Faso" <?php selected( $value,'Burkina Faso');?> ><?php _e('Burkina Faso','profile-grid');?></option>
<option value="Burundi" <?php selected( $value,'Burundi');?> ><?php _e('Burundi','profile-grid');?></option>
<option value="Cambodia" <?php selected( $value,'Cambodia');?> ><?php _e('Cambodia','profile-grid');?></option>
<option value="Cameroon" <?php selected( $value,'Cameroon');?> ><?php _e('Cameroon','profile-grid');?></option>
<option value="Canada" <?php selected( $value,'Canada');?> ><?php _e('Canada','profile-grid');?></option>
<option value="Cape Verde" <?php selected( $value,'Cape Verde');?> ><?php _e('Cape Verde','profile-grid');?></option>
<option value="Cayman Islands" <?php selected( $value,'Cayman Islands');?> ><?php _e('Cayman Islands','profile-grid');?></option>
<option value="Central African Republic" <?php selected( $value,'Central African Republic');?> ><?php _e('Central African Republic','profile-grid');?></option>
<option value="Chad" <?php selected( $value,'Chad');?> ><?php _e('Chad','profile-grid');?></option>
<option value="Chile" <?php selected( $value,'Chile');?> ><?php _e('Chile','profile-grid');?></option>
<option value="China" <?php selected( $value,'China');?> ><?php _e('China','profile-grid');?></option>
<option value="Christmas Island" <?php selected( $value,'Christmas Island');?> ><?php _e('Christmas Island','profile-grid');?></option>
<option value="Cocos (Keeling) Islands" <?php selected( $value,'Cocos (Keeling) Islands');?> ><?php _e('Cocos (Keeling) Islands','profile-grid');?></option>
<option value="Colombia" <?php selected( $value,'Colombia');?> ><?php _e('Colombia','profile-grid');?></option>
<option value="Comoros" <?php selected( $value,'Comoros');?> ><?php _e('Comoros','profile-grid');?></option>
<option value="Congo" <?php selected( $value,'Congo');?> ><?php _e('Congo','profile-grid');?></option>
<option value="Congo, The Democratic Republic of The" <?php selected( $value,'Congo, The Democratic Republic of The');?> ><?php _e('Congo, The Democratic Republic of The','profile-grid');?></option>
<option value="Cook Islands" <?php selected( $value,'Cook Islands');?> ><?php _e('Cook Islands','profile-grid');?></option>
<option value="Costa Rica" <?php selected( $value,'Costa Rica');?> ><?php _e('Costa Rica','profile-grid');?></option>
<option value="Cote D'ivoire" <?php selected( $value,'Cote D ivoire');?> ><?php _e('Cote D ivoire','profile-grid');?></option>
<option value="Croatia" <?php selected( $value,'Croatia');?> ><?php _e('Croatia','profile-grid');?></option>
<option value="Cuba" <?php selected( $value,'Cuba');?> ><?php _e('Cuba','profile-grid');?></option>
<option value="Cyprus" <?php selected( $value,'Cyprus');?> ><?php _e('Cyprus','profile-grid');?></option>
<option value="Czech Republic" <?php selected( $value,'Czech Republic');?> ><?php _e('Czech Republic','profile-grid');?></option>
<option value="Denmark" <?php selected( $value,'Denmark');?> ><?php _e('Denmark','profile-grid');?></option>
<option value="Djibouti" <?php selected( $value,'Djibouti');?> ><?php _e('Djibouti','profile-grid');?></option>
<option value="Dominica" <?php selected( $value,'Dominica');?> ><?php _e('Dominica','profile-grid');?></option>
<option value="Dominican Republic" <?php selected( $value,'Dominican Republic');?> ><?php _e('Dominican Republic','profile-grid');?></option>
<option value="Ecuador" <?php selected( $value,'Ecuador');?> ><?php _e('Ecuador','profile-grid');?></option>
<option value="Egypt" <?php selected( $value,'Egypt');?> ><?php _e('Egypt','profile-grid');?></option>
<option value="El Salvador" <?php selected( $value,'El Salvador');?> ><?php _e('El Salvador','profile-grid');?></option>
<option value="Equatorial Guinea" <?php selected( $value,'Equatorial Guinea');?> ><?php _e('Equatorial Guinea','profile-grid');?></option>
<option value="Eritrea" <?php selected( $value,'Eritrea');?> ><?php _e('Eritrea','profile-grid');?></option>
<option value="Estonia" <?php selected( $value,'Estonia');?> ><?php _e('Estonia','profile-grid');?></option>
<option value="Ethiopia" <?php selected( $value,'Ethiopia');?> ><?php _e('Ethiopia','profile-grid');?></option>
<option value="Falkland Islands (Malvinas)" <?php selected( $value,'Falkland Islands (Malvinas)');?> ><?php _e('Falkland Islands (Malvinas)','profile-grid');?></option>
<option value="Faroe Islands" <?php selected( $value,'Faroe Islands');?> ><?php _e('Faroe Islands','profile-grid');?></option>
<option value="Fiji" <?php selected( $value,'Fiji');?> ><?php _e('Fiji','profile-grid');?></option>
<option value="Finland" <?php selected( $value,'Finland');?> ><?php _e('Finland','profile-grid');?></option>
<option value="France" <?php selected( $value,'France');?> ><?php _e('France','profile-grid');?></option>
<option value="French Guiana" <?php selected( $value,'French Guiana');?> ><?php _e('French Guiana','profile-grid');?></option>
<option value="French Polynesia" <?php selected( $value,'French Polynesia');?> ><?php _e('French Polynesia','profile-grid');?></option>
<option value="French Southern Territories" <?php selected( $value,'French Southern Territories');?> ><?php _e('French Southern Territories','profile-grid');?></option>
<option value="Gabon" <?php selected( $value,'Gabon');?> ><?php _e('Gabon','profile-grid');?></option>
<option value="Gambia" <?php selected( $value,'Gambia');?> ><?php _e('Gambia','profile-grid');?></option>
<option value="Georgia" <?php selected( $value,'Georgia');?> ><?php _e('Georgia','profile-grid');?></option>
<option value="Germany" <?php selected( $value,'Germany');?> ><?php _e('Germany','profile-grid');?></option>
<option value="Ghana" <?php selected( $value,'Ghana');?> ><?php _e('Ghana','profile-grid');?></option>
<option value="Gibraltar" <?php selected( $value,'Gibraltar');?> ><?php _e('Gibraltar','profile-grid');?></option>
<option value="Greece" <?php selected( $value,'Greece');?> ><?php _e('Greece','profile-grid');?></option>
<option value="Greenland" <?php selected( $value,'Greenland');?> ><?php _e('Greenland','profile-grid');?></option>
<option value="Grenada" <?php selected( $value,'Grenada');?> ><?php _e('Grenada','profile-grid');?></option>
<option value="Guadeloupe" <?php selected( $value,'Guadeloupe');?> ><?php _e('Guadeloupe','profile-grid');?></option>
<option value="Guam" <?php selected( $value,'Guam');?> ><?php _e('Guam','profile-grid');?></option>
<option value="Guatemala" <?php selected( $value,'Guatemala');?> ><?php _e('Guatemala','profile-grid');?></option>
<option value="Guernsey" <?php selected( $value,'Guernsey');?> ><?php _e('Guernsey','profile-grid');?></option>
<option value="Guinea" <?php selected( $value,'Guinea');?> ><?php _e('Guinea','profile-grid');?></option>
<option value="Guinea-bissau" <?php selected( $value,'Guinea');?> ><?php _e('Guinea-bissau','profile-grid');?></option>
<option value="Guyana" <?php selected( $value,'Guyana');?> ><?php _e('Guyana','profile-grid');?></option>
<option value="Haiti" <?php selected( $value,'Haiti');?> ><?php _e('Haiti','profile-grid');?></option>
<option value="Heard Island and Mcdonald Islands" <?php selected( $value,'Heard Island and Mcdonald Islands');?> ><?php _e('Heard Island and Mcdonald Islands','profile-grid');?></option>
<option value="Holy See (Vatican City State)" <?php selected( $value,'Holy See (Vatican City State)');?> ><?php _e('Holy See (Vatican City State)','profile-grid');?></option>
<option value="Honduras" <?php selected( $value,'Honduras');?> ><?php _e('Honduras','profile-grid');?></option>
<option value="Hong Kong" <?php selected( $value,'Hong Kong');?> ><?php _e('Hong Kong','profile-grid');?></option>
<option value="Hungary" <?php selected( $value,'Hungary');?> ><?php _e('Hungary','profile-grid');?></option>
<option value="Iceland" <?php selected( $value,'Iceland');?> ><?php _e('Iceland','profile-grid');?></option>
<option value="India" <?php selected( $value,'India');?> ><?php _e('India','profile-grid');?></option>
<option value="Indonesia" <?php selected( $value,'Indonesia');?> ><?php _e('Indonesia','profile-grid');?></option>
<option value="Iran, Islamic Republic of" <?php selected( $value,'Iran, Islamic Republic of');?> ><?php _e('Iran, Islamic Republic of','profile-grid');?></option>
<option value="Iraq" <?php selected( $value,'Iraq');?> ><?php _e('Iraq','profile-grid');?></option>
<option value="Ireland" <?php selected( $value,'Ireland');?> ><?php _e('Ireland','profile-grid');?></option>
<option value="Isle of Man" <?php selected( $value,'Isle of Man');?> ><?php _e('Isle of Man','profile-grid');?></option>
<option value="Israel" <?php selected( $value,'Israel');?> ><?php _e('Israel','profile-grid');?></option>
<option value="Italy" <?php selected( $value,'Italy');?> ><?php _e('Italy','profile-grid');?></option>
<option value="Jamaica" <?php selected( $value,'Jamaica');?> ><?php _e('Jamaica','profile-grid');?></option>
<option value="Japan" <?php selected( $value,'Japan');?> ><?php _e('Japan','profile-grid');?></option>
<option value="Jersey" <?php selected( $value,'Jersey');?> ><?php _e('Jersey','profile-grid');?></option>
<option value="Jordan" <?php selected( $value,'Jordan');?> ><?php _e('Jordan','profile-grid');?></option>
<option value="Kazakhstan" <?php selected( $value,'Kazakhstan');?> ><?php _e('Kazakhstan','profile-grid');?></option>
<option value="Kenya" <?php selected( $value,'Kenya');?> ><?php _e('Kenya','profile-grid');?></option>
<option value="Kiribati" <?php selected( $value,'Kiribati');?> ><?php _e('Kiribati','profile-grid');?></option>
<option value="Korea, Democratic People's Republic of" <?php selected( $value,"Korea, Democratic People's Republic of");?> ><?php _e("Korea, Democratic People's Republic of",'profile-grid');?></option>
<option value="Korea, Republic of" <?php selected( $value,'Korea, Republic of');?> ><?php _e('Korea, Republic of','profile-grid');?></option>
<option value="Kuwait" <?php selected( $value,'Kuwait');?> ><?php _e('Kuwait','profile-grid');?></option>
<option value="Kyrgyzstan" <?php selected( $value,'Kyrgyzstan');?> ><?php _e('Kyrgyzstan','profile-grid');?></option>
<option value="Lao People's Democratic Republic" <?php selected( $value,"Lao People's Democratic Republic");?> ><?php _e("Lao People's Democratic Republic",'profile-grid');?></option>
<option value="Latvia" <?php selected( $value,'Latvia');?> ><?php _e('Latvia','profile-grid');?></option>
<option value="Lebanon" <?php selected( $value,'Lebanon');?> ><?php _e('Lebanon','profile-grid');?></option>
<option value="Lesotho" <?php selected( $value,'Lesotho');?> ><?php _e('Lesotho','profile-grid');?></option>
<option value="Liberia" <?php selected( $value,'Liberia');?> ><?php _e('Liberia','profile-grid');?></option>
<option value="Libyan Arab Jamahiriya" <?php selected( $value,'Libyan Arab Jamahiriya');?> ><?php _e('Libyan Arab Jamahiriya','profile-grid');?></option>
<option value="Liechtenstein" <?php selected( $value,'Liechtenstein');?> ><?php _e('Liechtenstein','profile-grid');?></option>
<option value="Lithuania" <?php selected( $value,'Lithuania');?> ><?php _e('Lithuania','profile-grid');?></option>
<option value="Luxembourg" <?php selected( $value,'Luxembourg');?> ><?php _e('Luxembourg','profile-grid');?></option>
<option value="Macao" <?php selected( $value,'Macao');?> ><?php _e('Macao','profile-grid');?></option>
<option value="Macedonia, The Former Yugoslav Republic of" <?php selected( $value,'Macedonia, The Former Yugoslav Republic of');?> ><?php _e('Macedonia, The Former Yugoslav Republic of','profile-grid');?></option>
<option value="Madagascar" <?php selected( $value,'Madagascar');?> ><?php _e('Madagascar','profile-grid');?></option>
<option value="Malawi" <?php selected( $value,'Malawi');?> ><?php _e('Malawi','profile-grid');?></option>
<option value="Malaysia" <?php selected( $value,'Malaysia');?> ><?php _e('Malaysia','profile-grid');?></option>
<option value="Maldives" <?php selected( $value,'Maldives');?> ><?php _e('Maldives','profile-grid');?></option>
<option value="Mali" <?php selected( $value,'Mali');?> ><?php _e('Mali','profile-grid');?></option>
<option value="Malta" <?php selected( $value,'Malta');?> ><?php _e('Malta','profile-grid');?></option>
<option value="Marshall Islands" <?php selected( $value,'Marshall Islands');?> ><?php _e('Marshall Islands','profile-grid');?></option>
<option value="Martinique" <?php selected( $value,'Martinique');?> ><?php _e('Martinique','profile-grid');?></option>
<option value="Mauritania" <?php selected( $value,'Mauritania');?> ><?php _e('Mauritania','profile-grid');?></option>
<option value="Mauritius" <?php selected( $value,'Mauritius');?> ><?php _e('Mauritius','profile-grid');?></option>
<option value="Mayotte" <?php selected( $value,'Mayotte');?> ><?php _e('Mayotte','profile-grid');?></option>
<option value="Mexico" <?php selected( $value,'Mexico');?> ><?php _e('Mexico','profile-grid');?></option>
<option value="Micronesia, Federated States of" <?php selected( $value,'Micronesia, Federated States of');?> ><?php _e('Micronesia, Federated States of','profile-grid');?></option>
<option value="Moldova, Republic of" <?php selected( $value,'Moldova, Republic of');?> ><?php _e('Moldova, Republic of','profile-grid');?></option>
<option value="Monaco" <?php selected( $value,'Monaco');?> ><?php _e('Monaco','profile-grid');?></option>
<option value="Mongolia" <?php selected( $value,'Mongolia');?> ><?php _e('Mongolia','profile-grid');?></option>
<option value="Montenegro" <?php selected( $value,'Montenegro');?> ><?php _e('Montenegro','profile-grid');?></option>
<option value="Montserrat" <?php selected( $value,'Montserrat');?> ><?php _e('Montserrat','profile-grid');?></option>
<option value="Morocco" <?php selected( $value,'Morocco');?> ><?php _e('Morocco','profile-grid');?></option>
<option value="Mozambique" <?php selected( $value,'Mozambique');?> ><?php _e('Mozambique','profile-grid');?></option>
<option value="Myanmar" <?php selected( $value,'Myanmar');?> ><?php _e('Myanmar','profile-grid');?></option>
<option value="Namibia" <?php selected( $value,'Namibia');?> ><?php _e('Namibia','profile-grid');?></option>
<option value="Nauru" <?php selected( $value,'Nauru');?> ><?php _e('Nauru','profile-grid');?></option>
<option value="Nepal" <?php selected( $value,'Nepal');?> ><?php _e('Nepal','profile-grid');?></option>
<option value="Netherlands" <?php selected( $value,'Netherlands');?> ><?php _e('Netherlands','profile-grid');?></option>
<option value="Netherlands Antilles" <?php selected( $value,'Netherlands Antilles');?> ><?php _e('Netherlands Antilles','profile-grid');?></option>
<option value="New Caledonia" <?php selected( $value,'New Caledonia');?> ><?php _e('New Caledonia','profile-grid');?></option>
<option value="New Zealand" <?php selected( $value,'New Zealand');?> ><?php _e('New Zealand','profile-grid');?></option>
<option value="Nicaragua" <?php selected( $value,'Nicaragua');?> ><?php _e('Nicaragua','profile-grid');?></option>
<option value="Niger" <?php selected( $value,'Niger');?> ><?php _e('Niger','profile-grid');?></option>
<option value="Nigeria" <?php selected( $value,'Nigeria');?> ><?php _e('Nigeria','profile-grid');?></option>
<option value="Niue" <?php selected( $value,'Niue');?> ><?php _e('Niue','profile-grid');?></option>
<option value="Norfolk Island" <?php selected( $value,'Norfolk Island');?> ><?php _e('Norfolk Island','profile-grid');?></option>
<option value="Northern Mariana Islands" <?php selected( $value,'Northern Mariana Islands');?> ><?php _e('Northern Mariana Islands','profile-grid');?></option>
<option value="Norway" <?php selected( $value,'Norway');?> ><?php _e('Norway','profile-grid');?></option>
<option value="Oman" <?php selected( $value,'Oman');?> ><?php _e('Oman','profile-grid');?></option>
<option value="Pakistan" <?php selected( $value,'Pakistan');?> ><?php _e('Pakistan','profile-grid');?></option>
<option value="Palau" <?php selected( $value,'Palau');?> ><?php _e('Palau','profile-grid');?></option>
<option value="Palestinian Territory, Occupied" <?php selected( $value,'Palestinian Territory, Occupied');?> ><?php _e('Palestinian Territory, Occupied','profile-grid');?></option>
<option value="Panama" <?php selected( $value,'Panama');?> ><?php _e('Panama','profile-grid');?></option>
<option value="Papua New Guinea" <?php selected( $value,'Papua New Guinea');?> ><?php _e('Papua New Guinea','profile-grid');?></option>
<option value="Paraguay" <?php selected( $value,'Paraguay');?> ><?php _e('Paraguay','profile-grid');?></option>
<option value="Peru" <?php selected( $value,'Peru');?> ><?php _e('Peru','profile-grid');?></option>
<option value="Philippines" <?php selected( $value,'Philippines');?> ><?php _e('Philippines','profile-grid');?></option>
<option value="Pitcairn" <?php selected( $value,'Pitcairn');?> ><?php _e('Pitcairn','profile-grid');?></option>
<option value="Poland" <?php selected( $value,'Poland');?> ><?php _e('Poland','profile-grid');?></option>
<option value="Portugal" <?php selected( $value,'Portugal');?> ><?php _e('Portugal','profile-grid');?></option>
<option value="Puerto Rico" <?php selected( $value,'Puerto Rico');?> ><?php _e('Puerto Rico','profile-grid');?></option>
<option value="Qatar" <?php selected( $value,'Qatar');?> ><?php _e('Qatar','profile-grid');?></option>
<option value="Reunion" <?php selected( $value,'Reunion');?> ><?php _e('Reunion','profile-grid');?></option>
<option value="Romania" <?php selected( $value,'Romania');?> ><?php _e('Romania','profile-grid');?></option>
<option value="Russian Federation" <?php selected( $value,'Russian Federation');?> ><?php _e('Russian Federation','profile-grid');?></option>
<option value="Rwanda" <?php selected( $value,'Rwanda');?> ><?php _e('Rwanda','profile-grid');?></option>
<option value="Saint Helena" <?php selected( $value,'Saint Helena');?> ><?php _e('Saint Helena','profile-grid');?></option>
<option value="Saint Kitts and Nevis" <?php selected( $value,'Saint Kitts and Nevis');?> ><?php _e('Saint Kitts and Nevis','profile-grid');?></option>
<option value="Saint Lucia" <?php selected( $value,'Saint Lucia');?> ><?php _e('Saint Lucia','profile-grid');?></option>
<option value="Saint Pierre and Miquelon" <?php selected( $value,'Saint Pierre and Miquelon');?> ><?php _e('Saint Pierre and Miquelon','profile-grid');?></option>
<option value="Saint Vincent and The Grenadines" <?php selected( $value,'Saint Vincent and The Grenadines');?> ><?php _e('Saint Vincent and The Grenadines','profile-grid');?></option>
<option value="Samoa" <?php selected( $value,'Samoa');?> ><?php _e('Samoa','profile-grid');?></option>
<option value="San Marino" <?php selected( $value,'San Marino');?> ><?php _e('San Marino','profile-grid');?></option>
<option value="Sao Tome and Principe" <?php selected( $value,'Sao Tome and Principe');?> ><?php _e('Sao Tome and Principe','profile-grid');?></option>
<option value="Saudi Arabia" <?php selected( $value,'Saudi Arabia');?> ><?php _e('Saudi Arabia','profile-grid');?></option>
<option value="Senegal" <?php selected( $value,'Senegal');?> ><?php _e('Senegal','profile-grid');?></option>
<option value="Serbia" <?php selected( $value,'Serbia');?> ><?php _e('Serbia','profile-grid');?></option>
<option value="Seychelles" <?php selected( $value,'Seychelles');?> ><?php _e('Seychelles','profile-grid');?></option>
<option value="Sierra Leone" <?php selected( $value,'Sierra Leone');?> ><?php _e('Sierra Leone','profile-grid');?></option>
<option value="Singapore" <?php selected( $value,'Singapore');?> ><?php _e('Singapore','profile-grid');?></option>
<option value="Slovakia" <?php selected( $value,'Slovakia');?> ><?php _e('Slovakia','profile-grid');?></option>
<option value="Slovenia" <?php selected( $value,'Slovenia');?> ><?php _e('Slovenia','profile-grid');?></option>
<option value="Solomon Islands" <?php selected( $value,'Solomon Islands');?> ><?php _e('Solomon Islands','profile-grid');?></option>
<option value="Somalia" <?php selected( $value,'Somalia');?> ><?php _e('Somalia','profile-grid');?></option>
<option value="South Africa" <?php selected( $value,'South Africa');?> ><?php _e('South Africa','profile-grid');?></option>
<option value="South Georgia and The South Sandwich Islands" <?php selected( $value,'South Georgia and The South Sandwich Islands');?> ><?php _e('South Georgia and The South Sandwich Islands','profile-grid');?></option>
<option value="Spain" <?php selected( $value,'Spain');?> ><?php _e('Spain','profile-grid');?></option>
<option value="Sri Lanka" <?php selected( $value,'Sri Lanka');?> ><?php _e('Sri Lanka','profile-grid');?></option>
<option value="Sudan" <?php selected( $value,'Sudan');?> ><?php _e('Sudan','profile-grid');?></option>
<option value="Suriname" <?php selected( $value,'Suriname');?> ><?php _e('Suriname','profile-grid');?></option>
<option value="Svalbard and Jan Mayen" <?php selected( $value,'Svalbard and Jan Mayen');?> ><?php _e('Svalbard and Jan Mayen','profile-grid');?></option>
<option value="Swaziland" <?php selected( $value,'Swaziland');?> ><?php _e('Swaziland','profile-grid');?></option>
<option value="Sweden" <?php selected( $value,'Sweden');?> ><?php _e('Sweden','profile-grid');?></option>
<option value="Switzerland" <?php selected( $value,'Switzerland');?> ><?php _e('Switzerland','profile-grid');?></option>
<option value="Syrian Arab Republic" <?php selected( $value,'Syrian Arab Republic');?> ><?php _e('Syrian Arab Republic','profile-grid');?></option>
<option value="Taiwan, Province of China" <?php selected( $value,'Taiwan, Province of China');?> ><?php _e('Taiwan, Province of China','profile-grid');?></option>
<option value="Tajikistan" <?php selected( $value,'Tajikistan');?> ><?php _e('Tajikistan','profile-grid');?></option>
<option value="Tanzania, United Republic of" <?php selected( $value,'Tanzania, United Republic of');?> ><?php _e('Tanzania, United Republic of','profile-grid');?></option>
<option value="Thailand" <?php selected( $value,'Thailand');?> ><?php _e('Thailand','profile-grid');?></option>
<option value="Timor-leste" <?php selected( $value,'Timor-leste');?> ><?php _e('Timor-leste','profile-grid');?></option>
<option value="Togo" <?php selected( $value,'Togo');?> ><?php _e('Togo','profile-grid');?></option>
<option value="Tokelau" <?php selected( $value,'Tokelau');?> ><?php _e('Tokelau','profile-grid');?></option>
<option value="Tonga" <?php selected( $value,'Tonga');?> ><?php _e('Tonga','profile-grid');?></option>
<option value="Trinidad and Tobago" <?php selected( $value,'Trinidad and Tobago');?> ><?php _e('Trinidad and Tobago','profile-grid');?></option>
<option value="Tunisia" <?php selected( $value,'Tunisia');?> ><?php _e('Tunisia','profile-grid');?></option>
<option value="Turkey" <?php selected( $value,'Turkey');?> ><?php _e('Turkey','profile-grid');?></option>
<option value="Turkmenistan" <?php selected( $value,'Turkmenistan');?> ><?php _e('Turkmenistan','profile-grid');?></option>
<option value="Turks and Caicos Islands" <?php selected( $value,'Turks and Caicos Islands');?> ><?php _e('Turks and Caicos Islands','profile-grid');?></option>
<option value="Tuvalu" <?php selected( $value,'Tuvalu');?> ><?php _e('Tuvalu','profile-grid');?></option>
<option value="Uganda" <?php selected( $value,'Uganda');?> ><?php _e('Uganda','profile-grid');?></option>
<option value="Ukraine" <?php selected( $value,'Ukraine');?> ><?php _e('Ukraine','profile-grid');?></option>
<option value="United Arab Emirates" <?php selected( $value,'United Arab Emirates');?> ><?php _e('United Arab Emirates','profile-grid');?></option>
<option value="United Kingdom" <?php selected( $value,'United Kingdom');?> ><?php _e('United Kingdom','profile-grid');?></option>
<option value="United States" <?php selected( $value,'United States');?>><?php _e('United States','profile-grid');?></option>
<option value="United States Minor Outlying Islands" <?php selected( $value,'United States Minor Outlying Islands');?> ><?php _e('United States Minor Outlying Islands','profile-grid');?></option>
<option value="Uruguay" <?php selected( $value,'Uruguay');?> ><?php _e('Uruguay','profile-grid');?></option>
<option value="Uzbekistan" <?php selected( $value,'Uzbekistan');?> ><?php _e('Uzbekistan','profile-grid');?></option>
<option value="Vanuatu" <?php selected( $value,'Vanuatu');?> ><?php _e('Vanuatu','profile-grid');?></option>
<option value="Venezuela" <?php selected( $value,'Venezuela');?> ><?php _e('Venezuela','profile-grid');?></option>
<option value="Viet Nam" <?php selected( $value,'Viet Nam');?> ><?php _e('Viet Nam','profile-grid');?></option>
<option value="Virgin Islands, British" <?php selected( $value,'Virgin Islands, British');?> ><?php _e('Virgin Islands, British','profile-grid');?></option>
<option value="Virgin Islands, U.S." <?php selected( $value,'Virgin Islands, U.S.');?> ><?php _e('Virgin Islands, U.S.','profile-grid');?></option>
<option value="Wallis and Futuna" <?php selected( $value,'Wallis and Futuna');?> ><?php _e('Wallis and Futuna','profile-grid');?></option>
<option value="Western Sahara" <?php selected( $value,'Western Sahara');?> ><?php _e('Western Sahara','profile-grid');?></option>
<option value="Yemen" <?php selected( $value,'Yemen');?> ><?php _e('Yemen','profile-grid');?></option>
<option value="Zambia" <?php selected( $value,'Zambia');?> ><?php _e('Zambia','profile-grid');?></option>
<option value="Zimbabwe" <?php selected( $value,'Zimbabwe');?> ><?php _e('Zimbabwe','profile-grid');?></option>